//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utable2
    {
        public int uid { get; set; }
        public string uname { get; set; }
        public string ugrade { get; set; }
        public Nullable<int> upercentage { get; set; }
    }
}
