//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatSupport
    {
        public int Id { get; set; }
        public string From_Email { get; set; }
        public string To_Email { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
