'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class dept
    Public Property deptno As Integer
    Public Property dname As String
    Public Property loc As String

    Public Overridable Property emps As ICollection(Of emp) = New HashSet(Of emp)

End Class
