'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class emp
    Public Property empno As Integer
    Public Property ename As String
    Public Property job As String
    Public Property salary As Nullable(Of Integer)
    Public Property deptno As Nullable(Of Integer)

    Public Overridable Property dept As dept

End Class
