'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class product
    Public Property productid As Integer
    Public Property productname As String
    Public Property price As Nullable(Of Integer)
    Public Property quantity As Nullable(Of Integer)

    Public Overridable Property sales As ICollection(Of sale) = New HashSet(Of sale)

End Class
