'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class sale
    Public Property salesid As Integer
    Public Property prdid As Nullable(Of Integer)
    Public Property sold As Nullable(Of Integer)
    Public Property product_name As String

    Public Overridable Property product As product

End Class
