//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Question2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int salesid { get; set; }
        public Nullable<int> prdid { get; set; }
        public Nullable<int> sold { get; set; }
        public string product_name { get; set; }
    
        public virtual product product { get; set; }
    }
}
